<?php

/**
 * Prevent Direct Access
 *
 * @since 0.1
 */
defined('ABSPATH') or die("Restricted access!");

/**
 * Register text domain
 *
 * @since 3.2
 */
function bestpreloader_textdomain() {
    load_plugin_textdomain( BESTPL_TEXT, false, BESTPL_DIR . '/languages/' );
}
add_action( 'init', 'bestpreloader_textdomain' );

/**
 * Print direct link to plugin admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the plugin admin page
 *
 * @since  3.2
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function bestpreloader_settings_link( $links ) {
    $page = '<a href="' . admin_url( 'options-general.php?page=best-preloader.php' ) .'">' . __( 'Settings', BESTPL_TEXT ) . '</a>';
    array_unshift( $links, $page );
    return $links;
}
add_filter( 'plugin_action_links_'.BESTPL_BASE, 'bestpreloader_settings_link' );

/**
 * Print additional links to plugin meta row
 *
 * @since 4.0
 */
function bestpreloader_plugin_row_meta( $links, $file ) {

    if ( strpos( $file, 'best-preloader.php' ) !== false ) {

        $new_links = array(
                           'donate' => '<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8A88KC7TFF6CS" target="_blank"><span class="dashicons dashicons-heart"></span> ' . __( 'Donate', BESTPL_TEXT ) . '</a>'
                           );
        $links = array_merge( $links, $new_links );
    }

    return $links;
}
add_filter( 'plugin_row_meta', 'bestpreloader_plugin_row_meta', 10, 2 );

/**
 * Register plugin's submenu in the "Settings" Admin Menu
 *
 * @since 4.0
 */
function bestpreloader_register_submenu_page() {
    add_options_page( __( 'Preloader', BESTPL_TEXT ), __( 'Preloader', BESTPL_TEXT ), 'manage_options', 'best-preloader', 'bestpreloader_render_submenu_page' );
}
add_action( 'admin_menu', 'bestpreloader_register_submenu_page' );

/**
 * Register settings
 *
 * @since 4.0
 */
function bestpreloader_register_settings() {
    register_setting( 'bestpreloader_settings_group', 'bestpreloader_settings' );
    register_setting( 'bestpreloader_settings_group', 'bestpreloader_service_info' );
}
add_action( 'admin_init', 'bestpreloader_register_settings' );
